Adapt to bevy latest (#2)
sburris0/bevy_flycam pull request #3
Opened 2021-04-06 10:25 UTC by HydrogenC

Same as #2.

2021-04-06 10:32 UTC, HydrogenC commented
It still doesn't pass the CI, I can't infer why. :(

2021-04-06 16:09 UTC, sburris0 commented
It looks like there were some syn problems upstream: https://github.com/bevyengine/bevy/commit/9193fc57d04fb492ac2b60cd75445930423f4425

If `cargo update` doesn't fix anything, I'll just wait until this gets sorted out to merge

2021-04-06 19:26 UTC, sburris0 commented
Might as well set the version to 0.5 now that it's out

2021-04-07 09:21 UTC, BlackPhlox requested changes

2021-04-07 09:21 UTC, BlackPhlox commented on src/lib.rs
> +        .with::<FlyCam>();
I ran your changes locally and get a build error here:
```
error[E0599]: no method named `with` found for struct `EntityCommands<'_, '_>` in the current scope
  --> src\lib.rs:59:10
   |
59 |         .with::<FlyCam>();
   |          ^^^^ method not found in `EntityCommands<'_, '_>`
```
Should be?:
```
.insert(FlyCam);
```
(Source: https://bevyengine.org/news/bevy-0-5/#entityref-entitymut)

2021-04-07 12:45 UTC, HydrogenC commented
Closed as there is a more complete PR (#4), but weirdly, it still doesn't pass the CI.

2021-04-07 12:45 UTC, closed without merging